[package]
name = "gelf-receiver"
version = "0.1.0"
authors = ["Mnwa <mihan@panfilov.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
actix = "0.9"
actix-rt = "0.2"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
flate2 = { version = "1.0", features = ["tokio"] }