version: '3'

services:
  sleep:
    build:
      dockerfile: Dockerfile
      context: .
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:8080"
        tag: "first-logs"
